import type { Metadata } from 'next'
import { Inter, Lexend_Deca } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter'})
const lexendDeca = Lexend_Deca({ subsets: ['latin'], variable: '--font-lexend-deca'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${lexendDeca.variable}`}>{children}</body>
    </html>
  )
}
