const interestOptions = [
	'Web Development',
	'Mobile Development',
	'UI/UX Design',
	'Cyber Security',
	'Data Science',
	'Artificial Intelligence',
	'Machine Learning',
	'Cloud Computing',
	'Internet of Things',
	'Blockchain',
	'Plumbing',
	'Welding',
	'Carpentry',
	'Masonry',
	'Electrical',
	'Mechanical',
	'Automotive',
	'Cookery',
	'Bartending',
	'Housekeeping',
	'Food and Beverage',
	'Front Office',
	'Tourism',
	'Events Management',
	'Animation',
];

const skillOptions = [
	'Construction',
	'Welding',
	'Plumbing',
	'Electrician',
	'Carpentry',
	'Auto Mechanic',
	'Heavy Equipment Operation',
	'Masonry',
	'Mechanical Repairs',
	'Building and Construction',
	'Landscaping',
	'HVAC Systems',
	'Vehicle Maintenance',
	'Manual Labor',
	'Safety Protocols',
	'Team Collaboration',
	'HTML',
	'CSS',
	'JavaScript',
	'React',
	'React Native',
	'NodeJS',
	'ExpressJS',
	'MongoDB',
	'MySQL',
	'Java',
];

// You can add or remove items based on specific blue-collar job requirements

export { skillOptions, interestOptions };
